### ISSUE TITLE
Поддержка дочерних шаблонов

### ISSUE THREAD

**Issue by EWG65** [bsakhanov/wmarka#1]
Здравствуйте!
Очень заинтересовал Ваш шаблон, но появился ряд существенных вопросов.
1. Планируете ли Вы делать поддержку дочерних шаблонов для Joomla! 4.1+ ?
2. Если не планируете, но планируете поддержку и обновление шаблона, то какие конкретно файлы будут обновляться? Если будет обновляться только index.php, то как прикручивать кастомные партикли? Если партикли тоже будут обновляться, то без поддержки дочернего шаблона всё теряет смысл, т.к. под каждый файл индекса или изменённый партикль создавать новую полную копию шаблона - совершенно нерентабельно.
3. Да, и папки css, images, js - должны полностью переезжать в папку media/tamplates/site (для Joomla! 4.1+), а они почему-то остаются и в папке templates.

Спасибо большое за Вашу работу!

**Comment by bsakhanov** [comment]
Прошу извинить за столь поздний отклик.

Поправил шаблон. 

1-2. Теперь можно создавать дочерние шаблоны. 

3. Папки css, images, js - теперь полностью переезжают в папку media/templates/site (для Joomla! 4.1+)

**Comment by EWG65** [comment]
Спасибо большое!
